### ISSUE TITLE
auth in cron

### ISSUE THREAD

**Issue by Costin-Nox** [OberstVonGatow/SpotifyReorder#1]
Hey, thanks for the great script. I'm not familiar with the spotify lib/spotify api. The script works great when running it from shell, i set it up to run as a cron task and the log is full of auth requests. 

Any clue how the auth happens, does it store some sort of session token somewhere that might be accessed differently when running as a cron (setup cron as same user that i ran the script manually as). I don't get the auth request when running it manually.

I'll glance over the code, but figured i'd ask and maybe update it myself if i find the answer as others might run into this!

Cheers!

**Comment by Costin-Nox** [comment]
Yup.. found the issue, so it will store a .cache-username in the folder you run the script in, i run the cron differently, so it doesnt find the file where it expects, modify the function

token = util.prompt_for_user_token(username,scope,client_id = client_id,client_secret = client_secret,redirect_uri='http://localhost/') and add cache_path='/whatever/you/want/.cache-tobe' to be

or this triggers:

cache_path = cache_path or ".cache-" + username

docs:
https://github.com/plamere/spotipy/blob/master/spotipy/util.py

**Comment by OberstVonGatow** [comment]
Hey, great you found an answer to the cache issue.
I will add it to the script tomorrow.

I also wondered where the token would be cached but for me it worked even with cron.
The script was only written in half a day with a lot of anger that spotify doesn't get it done itself.
If you have any other improvements suggestions, you are welcome.

**Comment by Costin-Nox** [comment]
> Hey, great you found an answer to the cache issue.
> I will add it to the script tomorrow.
> 
> I also wondered where the token would be cached but for me it worked even with cron.
> The script was only written in half a day with a lot of anger that spotify doesn't get it done itself.
> If you have any other improvements suggestions, you are welcome.

Most likely has to do with how i set my cron in my ubuntu container ( i added the interpreter at the top and run it as /path/to/script vs /bin/python /path/to script) i assume that makes it think the root folder is somewhere else, honestly this was an easier fix than sorting that out! It should be fine with default for most use cases. You did a great job, you saved me the half a day of angry coding because spotify doesn't support this and playing the lists in my car was incredibly annoying :). A note in the docs should be more than enough!
